### ISSUE TITLE
Intent filter for: BrowserTabActivity is missing

### ISSUE THREAD

**Issue by Sibisht** [stashenergy/react-native-msal#1] opened 2020-02-19 14:04 UTC
Hi I had followed exactly the same steps as mentioned but the error "Intent filter for: BrowserTabActivity is missing" kept coming even though I had added the activity with the intent-filter in the AndroidManifest.xml file.

**Comment by josmithua** [comment] 2020-02-19 18:00
Please post the whole error here. Are you trying to run the example app, or your own? If you're running your own you need to change the `android:path` property to include the correct base64 SHA1 signature from the keystore you are using.

**Comment by josmithua** [comment] 2020-02-21 14:15
Hey there @Sibisht, did you sort out your problem?

**Comment by josmithua** [comment] 2020-02-26 14:09
I'm going to close this, but if you have further related issues please feel free to comment here.

**Closed by josmithua** 2020-02-26 14:09 UTC

**Comment by Nealsoni00** [comment] 2021-02-24 16:10
This is happening to me as well. It worked previously (not sure when it broke) and I verified the `Signature hash` and `Redirect URI` are entered correctly in the msal_config.json and console as well as the `host` and `path` in the `AndroidManifest` using the `PublicClientApplication.showExpectedMsalRedirectUriInfo(this);` command. 

Any advice on how to resolve this would be amazing.

**Comment by josmithua** [comment] 2021-02-24 20:22
@Nealsoni00 are you using `react-native-msal`? Not sure why you would have that code creating a SingleAccountPublicClientApplication. `react-native-msal` does not support single account PCA

**Comment by fincha** [comment] 2021-03-02 12:52
@Nealsoni00 I have discovered, that in my msal_config.json the redirect URL:

> "redirect_uri": xxxx://auth",

this "auth" should be used as "host" in AndroidManifest

> <data android:scheme="xxxx" android:host="auth" />

**Comment by abdul-ahad-devs** [comment] 2021-11-25 12:43
I am facing the same issue, I have copied down exactly the same configs but I am getting browser activity issues as folows:

My AndroidManifest.xml:

```
      <!--Intent filter to capture authorization code response from the default browser on the device calling back to our app after interactive sign in -->
      <activity android:name="com.microsoft.identity.client.BrowserTabActivity">
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="msauth" android:host="com.checkmobileapp" android:path="/HASH_CODE" />
        </intent-filter>
      </activity>
```

The Error I am getting is:

index.bundle?platfor…false&runMod…:22804 Error: Intent filter for: BrowserTabActivity is missing.  Please make sure you have the following activity in your AndroidManifest.xml 

<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
	<intent-filter>
		<action android:name="android.intent.action.VIEW" />
		<category android:name="android.intent.category.DEFAULT" />
		<category android:name="android.intent.category.BROWSABLE" />
		<data
			android:host="com.checkmobileapp"
			android:path="/ga0RGNYHvNM5d0SLGQfpQWAPGJ8="
			android:scheme="msauth" />
	</intent-filter>
</activity>

I have tried all the solutions from internet but nothing worked for me.

**Comment by NightkingCH** [comment] 2021-12-04 12:51
Stumbled across this problem today. But for the moodio/msal-flutter library. The solution for me was not to use /HASH_CODE but /auth.

```
<activity
            android:name="com.microsoft.identity.client.BrowserTabActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="msauth" android:host="app.name" android:path="/auth" />
            </intent-filter>
        </activity>
```

**Comment by souvickcse** [comment] 2022-03-01 13:30
I was having same issue, when trying to use the code copy pasted, but after changing host, path on config json and manifest to my app specific the issue is solved.
