### ISSUE TITLE
acquireTokenSilent failing on ios

### ISSUE THREAD

**Issue by sbatikeri** [stashenergy/react-native-msal#71] opened 2021-03-23 18:43 UTC
**Describe the bug**

In some ios devices refresh token scenario is failing. I am storing user account in redux and passing that to acquireTokenSilent. As a fallback some blogs suggesting to use acquireTokenPopup but react-native-msal does not have this method. I used acquireToken for refresh token when it failed. 

Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=No account provided for the silent request. Please call interactive acquireToken request to get an account identifier before calling acquireTokenSilent.}

**To Reproduce**
const msalParams = {
        scopes: ["email"],
        account: userAccount,
      };
 
      return pca
        .acquireTokenSilent(msalParams)
        .then((response: any) => {
          
          Logger.log("Refresh token renewed successfully.");
          
          const { accessToken, refreshToken, idToken, account } = response;
          saveTokens(accessToken, idToken, idToken, account); 
          Logger.logError(new Error("----TOKEN REFRESHED------"));
          return _api(
            url,
            method,
            request,
            headers,
            retryCount,
            timeOut,
            idToken
          );
        })
        .catch((error) => {
          console.log("REFRESH TOKEN EXPIRED: ", error);
          Logger.verboseLog("Refresh token expired.");
          Logger.verboseLog("Force signout.");
          Logger.logError(error);
          signOut();
        });

**Expected behavior**

**Screenshots**

** Please complete the following information:**
  "react-native-msal": "^3.1.0",
"react-native": "^0.61.5",
 - IOS

**Additional context**

**Comment by josmithua** [comment] 2021-04-14 15:29
Duplicate of #76

**Closed by josmithua** 2021-04-14 15:29 UTC
