### ISSUE TITLE
acquireTokenSilent: No cached accounts found for the supplied homeAccountId and clientId

### ISSUE THREAD

**Issue by pabloromeu** [stashenergy/react-native-msal#11] opened 2020-04-30 14:02 UTC
I am continuously getting this error when trying to renew the token on Android. I can acquireToken, but cannot renew it. On iOS everything works smoothly

My msal_config.json:

```
{
  "client_id" : "792d30...",
  "redirect_uri" : "msauth://com..../QyXa9n...",
  "broker_redirect_uri_registered": true,
  "shared_device_mode_supported": true,
  "account_mode":"MULTIPLE",
  "authorities" : [
    {
      "type": "B2C",
      "authority_url": "https://....b2clogin.com/tfp/....onmicrosoft.com/B2C_1A_signup_signin_..."
    }
  ]
}
```

I am calling acquireTokenSilent with: 

```
               {
                    authority: "https://....b2clogin.com/tfp/....onmicrosoft.com/B2C_1A_signup_signin_",
                    scopes: ["aScope"],
                    accountIdentifier: "792d30...",
                    forceRefresh: true
                };
```
I always get the same error:

No cached accounts found for the supplied homeAccountId and clientId

**Comment by anwh** [comment] 2020-04-30 15:25
When I set: `broker_redirect_uri_registered = true` , my application crashes. What is the reason for this? And how I can fix it?

**Comment by pabloromeu** [comment] 2020-04-30 15:44
TBH, I did copy that line... I did get rid of it and nothing changes...

**Comment by josmithua** [comment] 2020-04-30 18:14
Hi @pabloromeu, I have not tested this library with `"broker_redirect_uri_registered": true` and `"shared_device_mode_supported": true`. Can you try to remove them / set them to false and see if it works? If that is the issue, I will look into adding support for it.

**Comment by pabloromeu** [comment] 2020-04-30 18:49
I did, and error persists... I think it has to do with clientId. AcquireToken does not get it so maybe acquireTokenSilent Filis for that. On iOS it works 🤷🏻‍♂️

**Comment by pabloromeu** [comment] 2020-04-30 19:08
First acquireToken call does not have idToken and username... Maybe that gives you a hint...

```
MSAL Service: Token acquired with auth: {
  "account": {
    "identifier": "GMJ2...-b2c_1a_signup_signin_whatever,
    "username": "Missing from the token response"
  },
  "tenantId": "a33d....,
  "authority": "https://whatever.b2clogin.com/tfp/whatever.onmicrosoft.com/B2C_1A_signup_signin_whatever",
  "scopes": [
    "https://whatever.onmicrosoft.com/79.../User.Read",
    "openid",
    "profile",
    "offline_access"
  ],
  "idToken": null,
  "expiresOn": "1588277155000",
  "accessToken": " a full access token"
}```

**Comment by josmithua** [comment] 2020-04-30 20:25
>  I think it has to do with idToken or username. AcquireToken does not get it so maybe acquireTokenSilent fails for that reason

The username and idToken has never been returned for me, yet it always works (for me), so I don't think that's the issue.

Could you try running the example app with your config?

**Comment by josmithua** [comment] 2020-04-30 20:27
Another possibility is that the Android MSAL library has been updated and a change has broke this library. If your problem persists with the example app I will take a deeper dive this weekend.

**Comment by pabloromeu** [comment] 2020-05-01 07:14
Configured, and tested @josmithua. acquireToken works, acquireTokenSilent fails:

![Fails](https://user-images.githubusercontent.com/3224197/80789304-e7915d80-8b8b-11ea-86db-4317553ccc7c.png)

P.D: I have tried to update the MSAL Android library to check if might be something related:
- Tested with the 1.3.0 --> Fails
- 1.4.1 --> Fails
- 1.5.0 --> Fails to build, problems with dependencies...

**Comment by josmithua** [comment] 2020-05-01 14:32
Thanks @pabloromeu, I will see if I can replicate the issue this weekend. Sorry you're having trouble with it.

**Comment by josmithua** [comment] 2020-05-02 19:52
@pabloromeu, I think you are passing the clientId in the `accountIdentifier` option instead of the account identifier.

You should be passing: 

`accountIdentifier: "GMJ2...-b2c_1a_signup_signin_whatever"`

not:

`accountIdentifier: "792d30..."`

**Comment by pabloromeu** [comment] 2020-05-03 06:36
@josmithua I verified it and no, my sample was wrong... I am passing the account.identifier indeed... I followed the example app. It fails at the example and at my App:

```
const acquireTokenSilent = async () => {
    if (authResult) {
      try {
        const res = await msalClient.acquireTokenSilent({
          authority: msalConfig.sisuAuthority,
          scopes: msalConfig.scopes,
          accountIdentifier: authResult.account.identifier,
        });
        handleResult(res);
      } catch (error) {
        console.warn(error);
      }
    }
  };
```

**Comment by josmithua** [comment] 2020-05-03 15:53
So far I cannot reproduce the error you are seeing. I have tested in the example app and a production app, both are working fine in Android. So it seems there's something in your configuration that the Android side of this library does not support currently. I would like to help get this working for you.

I misspoke earlier, I do receive an idToken back in the response (no username though), so you might be right, it may be an issue with that. You receive an idToken on iOS correct?

**Comment by pabloromeu** [comment] 2020-05-03 17:39
Yes! you are right @josmithua ... iOS returns an idToken! Maybe this has to do with my configuration? I have multiple AAD authorised through Azure B2C service... And the account I am trying to authorise is one of those domains. Or maybe it has to do with scopes? 
![Untitled](https://user-images.githubusercontent.com/3224197/80921253-8a590000-8d75-11ea-9237-1577491851d5.png)

**Comment by pabloromeu** [comment] 2020-05-04 06:21
Some more info. MSAL Native Library returns a rawIdToken:

![Screenshot 2020-05-04 at 08 18 20](https://user-images.githubusercontent.com/3224197/80940457-228bcf00-8de0-11ea-8468-f0ff058edc99.png)

But this token is not transferred to the callback:

![Screenshot 2020-05-04 at 08 18 31](https://user-images.githubusercontent.com/3224197/80940497-3a635300-8de0-11ea-94fb-2965dddca724.png)

**Comment by pabloromeu** [comment] 2020-05-04 06:51
Some more context... At MsalOauth2TokenCache file, this method:
```
 public ICacheRecord save(@NonNull final GenericOAuth2Strategy oAuth2Strategy,
                             @NonNull final GenericAuthorizationRequest request,
                             @NonNull final GenericTokenResponse response) throws ClientException 
```

Is returning everything but the idToken:

```
        final CacheRecord result = new CacheRecord();
        result.setAccount(accountToSave);
        result.setAccessToken(accessTokenToSave);
        result.setRefreshToken(refreshTokenToSave);
        setToCacheRecord(result, idTokenToSave); // HERE idToken is set to "cache" but not returned
```
Maybe it is not well cached... I think this might be a bug at the Android library cache...

**Comment by gitsad** [comment] 2020-05-06 12:41
It's probably issue with policy or issue with the android library itself. I had a conversation about it with Microsoft support. So far this issue is investigating.

**Comment by pabloromeu** [comment] 2020-05-06 12:46
Thanks for the helps @gitsad. I opened an issue as you can see by the mention at the Android library GitHub too as I think there is no issue at react-native-library.

**Comment by josmithua** [comment] 2020-06-17 14:11
Hi @pabloromeu, did you ever get this working?

**Comment by pabloromeu** [comment] 2020-06-18 08:56
Hi @josmithua,

No, I still have an open support ticket with Microsoft B2C Team. They have been able to reproduce the problem and they are trying to fix it.

**Comment by josmithua** [comment] 2020-06-18 11:53
Ok. Seeing as it’s not a direct issue with this library, I’m going to close this issue. I hope Microsoft gets it fixed soon!

**Closed by josmithua** 2020-06-18 11:53 UTC
